//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRentalTABLE
    {
        public int id { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerSurname { get; set; }
        public string CustomerAddress { get; set; }
        public Nullable<int> CustomerAge { get; set; }
        public string DrivingLicence { get; set; }
        public Nullable<int> NumberOfDays { get; set; }
        public Nullable<int> CarTypeId { get; set; }
        public Nullable<int> FuelTypeId { get; set; }
        public Nullable<int> ServicesId { get; set; }
    
        public virtual FuelType FuelType { get; set; }
        public virtual Service Service { get; set; }
        public virtual TypesOfCar TypesOfCar { get; set; }
    }
}
